### ISSUE TITLE
TP Fini

### ISSUE THREAD

**Issue by GreyHopes** [PolytechLyon/2019-isi3-graph-cellard-chlebowksi#1]
Salut Antoine, on a fini le TP. Est ce que tu pourrais nous faire tes retours sur ce qu'on a fait ?
Bonne soirée :smiley:

**Comment by Slashgear** [comment]
- [ ] Pourriez vous me représenter l'UML du pattern adapter utilisé avec le Graph ?
- [ ] Ici vous retournez une List de noeuds, devrions nous changer le contrat pour retourner un Set<Node> ? Si oui pourquoi ?
https://github.com/PolytechLyon/2019-isi3-graph-cellard-chlebowksi/blob/347ed57bbdc86864e4260cb2515dbb74d4a3e75d/src/main/java/graph/DirectedGraph.java#L51-L54
- [ ] La il y a plus simple, vous connaissez l'interface Map ? 
https://github.com/PolytechLyon/2019-isi3-graph-cellard-chlebowksi/blob/347ed57bbdc86864e4260cb2515dbb74d4a3e75d/src/main/java/graph/DirectedGraph.java#L56-L64

Sinon c'est pas mal, surtout la partie Iterator 👍

**Comment by GreyHopes** [comment]
Merci pour les retours on va essayer d'y jeter un oeil rapidement :sweat_smile:

**Comment by GreyHopes** [comment]
On vient de commit les changements relatifs à tes retours : 

* On a mis l'UML dans le rapport
* Après recherches on a juste besoin d'un Set, la différence majeure entre un Set et une List, c'est que Set n'est pas ordonné et chaque élément est unique ce qui dans notre cas n'est pas dérageant vu qu'on utilise le résultat de cette méthode uniquement pour parcourir les noeuds.
* On s'est rendu compte qu'on avait pas besoin de tous ces tests et qu'on pouvait juste retourner le résultat de `this.nodeEdgeMap.keySet().size()` vu qu'elle renvoie 0 si la map est vide

**Comment by Slashgear** [comment]
⚠️ On touche pas à mes commentaires :wink:
